name: ci

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      -
        name: Build the Docker image
        run: docker build -t personalwebsite:latest
      -
        name: Tag the Docker image
        run: docker tag personalwebsite:latest personalwebsite:1.0
      -
        name: Push the Docker image to the registry
        run: docker push personalwebsite:1.0
